FROM node:22.14.0-alpine

ARG APP_PATH=apps/admin

# Install pnpm globally
RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app/packages/contracts
COPY ./packages/contracts/package.json ./
RUN pnpm install

WORKDIR /app/${APP_PATH}

COPY ${APP_PATH}/package.json  ./

RUN pnpm install

COPY ${APP_PATH} .

WORKDIR /app
COPY ./packages/ ./packages/

WORKDIR /app/${APP_PATH}

CMD ["pnpm", "run", "dev"]
