FROM node:22.14.0-alpine

# Install pnpm globally
RUN corepack enable && corepack prepare pnpm@latest --activate

ARG APP_PATH=apps/api

WORKDIR /app/${APP_PATH}

COPY ${APP_PATH}/package.json  ./

RUN pnpm install

COPY ${APP_PATH}/prisma ./prisma

RUN pnpm prisma generate

COPY ${APP_PATH} .

WORKDIR /app
COPY ./packages/ ./packages/

WORKDIR /app/${APP_PATH}

CMD ["pnpm", "run", "dev"]
