FROM node:22.14.0-alpine AS admin_build

RUN corepack enable && corepack prepare pnpm@latest --activate


WORKDIR /app

COPY ./apps/web/package.json ./

RUN pnpm install

COPY ./apps/web/ .

ARG NEXT_PUBLIC_API_URL

RUN pnpm build

CMD ["pnpm", "start"]
